<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <RootNamespace>OsuScraper</RootNamespace>
    <StartupObject>OsuScraper.My.MyApplication</StartupObject>
    <UseWindowsForms>True</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <OptionStrict>On</OptionStrict>
    <Authors>Ziddy</Authors>
    <Company />
    <ApplicationIcon>Resources\os_icon.ico</ApplicationIcon>
    <Title>OsuScraper</Title>
    <Description>Scrapes Osu! for beatmap packs and keeps track of which packs are owned </Description>
    <Copyright>© 2024 All Rights Reserved</Copyright>
    <PackageIcon>os_icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/Ziddykins/OsuScraper</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>en</NeutralLanguage>
    <AssemblyVersion>2.2</AssemblyVersion>
    <FileVersion>2.2</FileVersion>
    <UseWPF>False</UseWPF>
    <Version></Version>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn />
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn />
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\os_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Desktop\os_icon.png" Link="Resources\os_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="bin\Debug\net8.0-windows10.0.22621.0\.packs_cache" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Guna.Charts.WinForms" Version="1.0.9" />
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PeanutButter.INI" Version="3.0.291" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="System.CodeDom" Version="8.0.0" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.118" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.4" />
    <PackageReference Include="System.Windows.Extensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="My Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="My Project\Settings.settings">
      <CustomToolNamespace>My</CustomToolNamespace>
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="obj\Debug\" />
  </ItemGroup>

</Project>